server:
  port: 9090
management:
  security:
    enabled: false
spring:
  datasource:
    url: jdbc:hive2://localhost:10000/airline
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: org.apache.hive.jdbc.HiveDriver
    username: fengxuechao
    password: fengxuechao
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fengxuechao.example.hive.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
