server:
  port: 9090
management:
  security:
    enabled: false
spring:
  datasource:
    url: jdbc:hive2://localhost:10000/airline
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.apache.hive.jdbc.HiveDriver
    username: test
    password: 654321
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fengxuechao.example.hive.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 自定义aop日志
aop.log.expression: "execution(* com.awifi.capacity.stats.smarthome.review.bind.service..*.*(..))"
